# Generated by Django 2.2.3 on 2020-06-09 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bigoraphy',
            new_name='biography',
        ),
    ]
